### PR TITLE
Enable JSON linting

### LINKED ISSUE #50: Add json linting
It would be really nice if lint-review could lint .json files. Possibly with https://www.npmjs.com/package/jsonlint

### PR DESCRIPTION
**Pull request by ddub**
using the python module demjson which provides a jsonlint script
Which prevents needing to install an external npm module and also the
npm module seems to stop after the first warning.

Fixes #50

### CODE REVIEW

**Comment by markstory** [comment]
Nice work!

**Comment by adrianmoisey** [comment]
Thanks ddub! I has no idea that `demjson` existed.

**Comment by adrianmoisey** [comment]
@markstory could you bump the version and publish to pypi please? I'd like to roll this out.

**Comment by markstory** [comment]
@adrianmoisey I can do that tonight. I don't have my gpg keys at work.

**Comment by adrianmoisey** [comment]
:+1: Thanks

**Pull request merged**
