### PR TITLE
Comment aggregation

### PR DESCRIPTION
**Pull request by markstory**
These changes add per-line comment aggregation. Some of the tools can be quite chatty and result in multiple comments on a single line. With these changes only a single comment is made on each line instead of multiple.

This should make lint-review less spammy and more friendly :smile:

### CODE REVIEW

**Comment by skaasten** [comment]
Thank you!

**Comment by alexBaizeau** [comment]
:clap:

**Comment by minichate** [comment]
:100:

**Comment by adrianmoisey** [comment]
neat

**Comment by AntonNguyen** [comment]
:clap:

**Pull request merged**
