### PR TITLE
Replace the dead pygithub3 with github3.py

### PR DESCRIPTION
**Pull request by adrianmoisey**
Since `pygithub3` is dead I thought I'd try switch lint-review across to `github3.py` (which is totally awesome, by the way).

Unfortunately the tests are quite tightly integrated with `pygithub3`, so I haven't fixed any of those yet.

If anyone wants to help out, that would be epic.

### CODE REVIEW

**Comment by markstory** [comment]
Only 10 failures, that's not so bad. I'll take a look this weekend and possibly send you a pull request :smile:

**Comment by markstory** [comment]
Looks like I missed a few tests because I still had pygithub3 installed. I'll get those remaining tests fixed.

**Comment by markstory** [comment]
Thanks @adrianmoisey! I did some manual testing tonight and everything looks good :+1:

**Comment by adrianmoisey** [comment]
\o/

Thanks for your help too!

**Pull request merged**
